### ISSUE TITLE
Array index calls, e.g. "arr[0]" gets rewritten to "arr."

### ISSUE THREAD

**Issue by fabianrichter** [HubSpot/prettier-plugin-hubl#68]
**Description**

I was trying the code formatting plugin today and played around with it. I recognized a breaking rewrite:
When calling an index of an array, e.g. `array[0]` it gets rewritten to `array.`.

**Expected behavior**

It should stay the same.

**To Reproduce**

Original Source Code:
```jinja2
{% set arr = ["foo", "bar"] %}
{{ arr[1] }}
```

Formatted Source Code:
```jinja2
{% set arr = [ "foo", "bar"] %}
{{ arr. }}
```

**Checklist**

- [x] I have checked the [known issues](https://github.com/HubSpot/prettier-plugin-hubl/issues/18) to make sure this isn’t already a known issue.

**Comment by j-malt** [comment]
I'm not able to reproduce this bug, and I can't really see how it would be happening ([since there is a check on the type of the value before the rewrite](https://github.com/HubSpot/prettier-plugin-hubl/blob/a3b17a1abad479ee4d90b9274ded0b24745fe328/prettier/src/printHubl.ts#L273-L275) that caused #70), but in any case, there is a fix for #70 in PR #77 that should add some additional safety for this. Do let us know if you have a more consistent reproduction method.
