### ISSUE TITLE
Is this maintained and do you want a PR to bump to Prettier 3?

### ISSUE THREAD

**Issue by happycollision** [HubSpot/prettier-plugin-hubl#75]
I upgraded this package and fixed an issue with `/*styleblockN*;`.

Do you want me to clean it up a bit and PR, or should we just go with our own fork and call this one dead?

**Comment by happycollision** [comment]
Hey @j-malt! I see you "trying to fix" some problems after upgrading to prettier 3. I've already done some of that work if you are interested.

I've got two branches in my forked repo. [`prettier-3`](https://github.com/happycollision/prettier-plugin-hubl/tree/prettier-3) is the branch I used to just hammer through things. Tests pass the same way they did with prettier 2 (which means not all passing). [`alt-prettier-3`](https://github.com/happycollision/prettier-plugin-hubl/tree/alt-prettier-3) is the one I am doing to create a more understandable git history that'd get you to approximately the same place. I am also trying to leave my opinionated stuff until the end—so that you don't have to adopt NPM workspaces if you are against it for some reason, for example.

**Comment by jsines** [comment]
Oops - did not mean to close, apologies 🥲

**Comment by j-malt** [comment]
Hi @happycollision! Nice catch - forgot to switch branches 😆

This project _is_ maintained and we do intend to bump prettier version, start clearing out the issue backlog, and hopefully continue to work to improve the project and get it out of beta. Apologies for the delay in updates here, I know the plugin is a pretty important part of some of our developers workflows.

--- 

Regarding your pair of branches: Your current work looks great and is very appreciated! There are some "opinionated" things that we'd probably not want to take (we prefer to use `yarn` instead of `npm`, probably lerna instead of npm workspaces, etc.), but feel free to put up a couple PRs with your changes and we can look it over and have a bit more involved discussion.

**Comment by happycollision** [comment]
Sounds good. I tried to leave the opinionated stuff for the end so those commits could be just dropped.

I didn’t realize that yarn would be a no-go since you already had a package-lock file, but that’s easy enough to change.

**Comment by j-malt** [comment]
👋 Hi @happycollision. I've just put up #76 that includes your fix for the style block bug (and bumps to prettier v3, reworks project configuration, etc.). We will publish a new version of this package soon that will include these changes.

Thank you for the report and all your work on this!

**Comment by happycollision** [comment]
You bet.
